/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramón Samayoa, Diego Valdez, Sang Wo Shin
 */
public class RadioGUI extends javax.swing.JFrame {
    private boolean btnGuardar;
    Radio radio = new Radio(false, "AM", "530");
    
    
    /**
     * Creates new form RadioGUI
     */
    public RadioGUI() {
        initComponents();
        btnGuardar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDisplay = new javax.swing.JPanel();
        lbFrequency = new javax.swing.JLabel();
        lbStation = new javax.swing.JLabel();
        lbCH = new javax.swing.JLabel();
        bEstado = new javax.swing.JToggleButton();
        bFrequency = new javax.swing.JToggleButton();
        pBotones = new javax.swing.JPanel();
        bCH1 = new javax.swing.JButton();
        bCH2 = new javax.swing.JButton();
        bCH3 = new javax.swing.JButton();
        bCH4 = new javax.swing.JButton();
        bCH5 = new javax.swing.JButton();
        bCH6 = new javax.swing.JButton();
        bCH8 = new javax.swing.JButton();
        bCH9 = new javax.swing.JButton();
        bCH10 = new javax.swing.JButton();
        bCH11 = new javax.swing.JButton();
        bCH12 = new javax.swing.JButton();
        bCH7 = new javax.swing.JButton();
        bBackward = new javax.swing.JButton();
        bForward = new javax.swing.JButton();
        bSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Radio");

        pDisplay.setBackground(new java.awt.Color(159, 202, 165));
        pDisplay.setEnabled(false);

        lbFrequency.setFont(new java.awt.Font("DS-Digital", 1, 70)); // NOI18N
        lbFrequency.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbFrequency.setText("AM");

        lbStation.setFont(new java.awt.Font("DS-Digital", 1, 70)); // NOI18N
        lbStation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStation.setText(" ");

        lbCH.setFont(new java.awt.Font("DS-Digital", 1, 36)); // NOI18N
        lbCH.setText("CH");

        javax.swing.GroupLayout pDisplayLayout = new javax.swing.GroupLayout(pDisplay);
        pDisplay.setLayout(pDisplayLayout);
        pDisplayLayout.setHorizontalGroup(
            pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDisplayLayout.createSequentialGroup()
                        .addComponent(lbFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbStation, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbCH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDisplayLayout.setVerticalGroup(
            pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStation, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bEstado.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        bEstado.setText("OFF");
        bEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEstado.setMaximumSize(new java.awt.Dimension(90, 45));
        bEstado.setMinimumSize(new java.awt.Dimension(90, 45));
        bEstado.setPreferredSize(new java.awt.Dimension(90, 45));
        bEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadoActionPerformed(evt);
            }
        });

        bFrequency.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bFrequency.setText("AM/FM");
        bFrequency.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFrequency.setEnabled(false);
        bFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFrequencyActionPerformed(evt);
            }
        });

        pBotones.setEnabled(false);

        bCH1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH1.setText("1");
        bCH1.setEnabled(false);
        bCH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH1ActionPerformed(evt);
            }
        });

        bCH2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH2.setText("2");
        bCH2.setEnabled(false);
        bCH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH2ActionPerformed(evt);
            }
        });

        bCH3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH3.setText("3");
        bCH3.setEnabled(false);
        bCH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH3ActionPerformed(evt);
            }
        });

        bCH4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH4.setText("4");
        bCH4.setEnabled(false);
        bCH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH4ActionPerformed(evt);
            }
        });

        bCH5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH5.setText("5");
        bCH5.setEnabled(false);
        bCH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH5ActionPerformed(evt);
            }
        });

        bCH6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH6.setText("6");
        bCH6.setEnabled(false);
        bCH6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH6ActionPerformed(evt);
            }
        });

        bCH8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH8.setText("8");
        bCH8.setEnabled(false);
        bCH8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH8ActionPerformed(evt);
            }
        });

        bCH9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH9.setText("9");
        bCH9.setEnabled(false);
        bCH9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH9ActionPerformed(evt);
            }
        });

        bCH10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH10.setText("10");
        bCH10.setEnabled(false);
        bCH10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH10ActionPerformed(evt);
            }
        });

        bCH11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH11.setText("11");
        bCH11.setEnabled(false);
        bCH11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH11ActionPerformed(evt);
            }
        });

        bCH12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH12.setText("12");
        bCH12.setEnabled(false);
        bCH12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH12ActionPerformed(evt);
            }
        });

        bCH7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bCH7.setText("7");
        bCH7.setEnabled(false);
        bCH7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCH7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotonesLayout = new javax.swing.GroupLayout(pBotones);
        pBotones.setLayout(pBotonesLayout);
        pBotonesLayout.setHorizontalGroup(
            pBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotonesLayout.createSequentialGroup()
                .addGroup(pBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBotonesLayout.createSequentialGroup()
                        .addComponent(bCH7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBotonesLayout.createSequentialGroup()
                        .addComponent(bCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCH6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBotonesLayout.setVerticalGroup(
            pBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotonesLayout.createSequentialGroup()
                .addGroup(pBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCH1)
                    .addComponent(bCH2)
                    .addComponent(bCH3)
                    .addComponent(bCH4)
                    .addComponent(bCH5)
                    .addComponent(bCH6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCH7)
                    .addComponent(bCH8)
                    .addComponent(bCH10)
                    .addComponent(bCH12)
                    .addComponent(bCH11)
                    .addComponent(bCH9)))
        );

        bBackward.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bBackward.setText("<");
        bBackward.setEnabled(false);
        bBackward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackwardActionPerformed(evt);
            }
        });

        bForward.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bForward.setText(">");
        bForward.setEnabled(false);
        bForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bForwardActionPerformed(evt);
            }
        });

        bSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSave.setText("Guardar");
        bSave.setEnabled(false);
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(bBackward, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bForward, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(bEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bFrequency)
                    .addComponent(bSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBackward)
                    .addComponent(bForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void bEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadoActionPerformed
        boolean estado = radio.isOn();

        if(estado == false){
            bFrequency.setEnabled(true);
            bBackward.setEnabled(true);
            bForward.setEnabled(true);
            bSave.setEnabled(true);
            lbFrequency.setEnabled(true);
            lbCH.setEnabled(true);
            pBotones.setEnabled(true);
            
            bCH1.setEnabled(true);
            bCH2.setEnabled(true);
            bCH3.setEnabled(true);
            bCH4.setEnabled(true);
            bCH5.setEnabled(true);
            bCH6.setEnabled(true);
            bCH7.setEnabled(true);
            bCH8.setEnabled(true);
            bCH9.setEnabled(true);
            bCH10.setEnabled(true);
            bCH11.setEnabled(true);
            bCH12.setEnabled(true);
            
            radio.OnOff(true);
            bEstado.setText("ON");
            lbStation.setText(radio.getStation());
        }
        else{
            bFrequency.setEnabled(false);
            bBackward.setEnabled(false);
            bForward.setEnabled(false);
            bSave.setEnabled(false);
            lbFrequency.setEnabled(false);
            lbCH.setEnabled(false);
            pBotones.setEnabled(false);
            
            bCH1.setEnabled(false);
            bCH2.setEnabled(false);
            bCH3.setEnabled(false);
            bCH4.setEnabled(false);
            bCH5.setEnabled(false);
            bCH6.setEnabled(false);
            bCH7.setEnabled(false);
            bCH8.setEnabled(false);
            bCH9.setEnabled(false);
            bCH10.setEnabled(false);
            bCH11.setEnabled(false);
            bCH12.setEnabled(false);
            
            radio.OnOff(false);
            bEstado.setText("OFF");
            lbStation.setText("");
        }
    }//GEN-LAST:event_bEstadoActionPerformed

    private void bFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFrequencyActionPerformed
        String estado = radio.getFrequency();
        if(estado.equals("AM")){
            radio.setFrequency("FM");
            lbFrequency.setText(radio.getFrequency());
            
            radio.setStation("87.9");
            lbStation.setText(radio.getStation());
        }
        else{
            radio.setFrequency("AM");
            lbFrequency.setText(radio.getFrequency());
            
            radio.setStation("530");
            lbStation.setText(radio.getStation());
        }
    }//GEN-LAST:event_bFrequencyActionPerformed

    private void bForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bForwardActionPerformed
        lbCH.setText("CH");
        radio.Forward(radio.getFrequency(), radio.getStation());
        lbStation.setText(radio.getStation());
    }//GEN-LAST:event_bForwardActionPerformed

    private void bBackwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackwardActionPerformed
        lbCH.setText("CH");
        radio.Backward(radio.getFrequency(), radio.getStation());
        lbStation.setText(radio.getStation());
    }//GEN-LAST:event_bBackwardActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        btnGuardar = true;
    }//GEN-LAST:event_bSaveActionPerformed

    private void bCH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH1ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(0, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(0);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 1");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH1ActionPerformed

    private void bCH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH2ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(1, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(1);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 2");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH2ActionPerformed

    private void bCH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH3ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(2, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(2);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 3");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH3ActionPerformed

    private void bCH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH4ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(3, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(3);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 4");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH4ActionPerformed

    private void bCH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH5ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(4, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(4);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 5");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH5ActionPerformed

    private void bCH6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH6ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(5, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(5);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 6");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH6ActionPerformed

    private void bCH7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH7ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(6, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(6);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 7");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH7ActionPerformed

    private void bCH8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH8ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(7, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(7);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 8");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH8ActionPerformed

    private void bCH9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH9ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(8, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(8);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 9");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH9ActionPerformed

    private void bCH10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH10ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(9, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(9);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 10");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH10ActionPerformed

    private void bCH11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH11ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(10, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(10);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 11");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH11ActionPerformed

    private void bCH12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCH12ActionPerformed
        if(btnGuardar == true){
            radio.setMemory(11, Double.parseDouble(radio.getStation()));
        }
        else{
            String emisora = radio.selectMemory(11);
            if((Double.parseDouble(emisora)) != 0){
                radio.setStation(emisora);
                lbStation.setText(radio.getStation());
                lbCH.setText("CH 12");}
        }
        btnGuardar = false;
    }//GEN-LAST:event_bCH12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBackward;
    private javax.swing.JButton bCH1;
    private javax.swing.JButton bCH10;
    private javax.swing.JButton bCH11;
    private javax.swing.JButton bCH12;
    private javax.swing.JButton bCH2;
    private javax.swing.JButton bCH3;
    private javax.swing.JButton bCH4;
    private javax.swing.JButton bCH5;
    private javax.swing.JButton bCH6;
    private javax.swing.JButton bCH7;
    private javax.swing.JButton bCH8;
    private javax.swing.JButton bCH9;
    private javax.swing.JToggleButton bEstado;
    private javax.swing.JButton bForward;
    private javax.swing.JToggleButton bFrequency;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lbCH;
    private javax.swing.JLabel lbFrequency;
    private javax.swing.JLabel lbStation;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pDisplay;
    // End of variables declaration//GEN-END:variables
}
