/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramón Samayoa
 */
public class RadioGUI extends javax.swing.JFrame {

    Radio radio = new Radio(false, false, 510);
    /**
     * Creates new form RadioGUI
     */
    public RadioGUI() {
        initComponents();
        addButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDisplay = new javax.swing.JPanel();
        lbFrequency = new javax.swing.JLabel();
        lbEstacion = new javax.swing.JLabel();
        lbBoton = new javax.swing.JLabel();
        bEstado = new javax.swing.JToggleButton();
        bFrequency = new javax.swing.JToggleButton();
        pBotones = new javax.swing.JPanel();
        bBackward = new javax.swing.JButton();
        bForward = new javax.swing.JButton();
        bSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Radio");
        setResizable(false);

        pDisplay.setBackground(new java.awt.Color(159, 202, 165));
        pDisplay.setEnabled(false);

        lbFrequency.setFont(new java.awt.Font("DS-Digital", 1, 70)); // NOI18N
        lbFrequency.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbFrequency.setText("AM");

        lbEstacion.setFont(new java.awt.Font("DS-Digital", 1, 70)); // NOI18N
        lbEstacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEstacion.setText(" ");

        lbBoton.setFont(new java.awt.Font("DS-Digital", 1, 36)); // NOI18N
        lbBoton.setText("CH");

        javax.swing.GroupLayout pDisplayLayout = new javax.swing.GroupLayout(pDisplay);
        pDisplay.setLayout(pDisplayLayout);
        pDisplayLayout.setHorizontalGroup(
            pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lbEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pDisplayLayout.setVerticalGroup(
            pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bEstado.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        bEstado.setText("OFF");
        bEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEstado.setMaximumSize(new java.awt.Dimension(90, 45));
        bEstado.setMinimumSize(new java.awt.Dimension(90, 45));
        bEstado.setPreferredSize(new java.awt.Dimension(90, 45));
        bEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadoActionPerformed(evt);
            }
        });

        bFrequency.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bFrequency.setText("AM/FM");
        bFrequency.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFrequency.setEnabled(false);
        bFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFrequencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotonesLayout = new javax.swing.GroupLayout(pBotones);
        pBotones.setLayout(pBotonesLayout);
        pBotonesLayout.setHorizontalGroup(
            pBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pBotonesLayout.setVerticalGroup(
            pBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        bBackward.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bBackward.setText("<");
        bBackward.setEnabled(false);

        bForward.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bForward.setText(">");
        bForward.setEnabled(false);

        bSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSave.setText("Guardar");
        bSave.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(bEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bFrequency)
                            .addComponent(bSave)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(bBackward, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bForward, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBackward)
                    .addComponent(bForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSave)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtons(){
        javax.swing.JButton[] Botones = new javax.swing.JButton[12];
        for(int i=0;i<12;i++){
            for(int j=1;j<=2;j++)
            {
                javax.swing.JButton boton= new javax.swing.JButton(String.valueOf(i));
                Botones[i] = boton;
                pBotones.add(boton);
            }
        }
    }
    
    private void bEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadoActionPerformed
        boolean estado = radio.isOn();

        if(estado == false){
            bBackward.setEnabled(true);
            bForward.setEnabled(true);
            bSave.setEnabled(true);
            bFrequency.setEnabled(true);
            pBotones.setEnabled(true);
            radio.On(true);
            bEstado.setText("ON");
        }
        else{
            bBackward.setEnabled(false);
            bForward.setEnabled(false);
            bSave.setEnabled(false);
            bFrequency.setEnabled(false);
            pBotones.setEnabled(false);
            radio.On(false);
            bEstado.setText("OFF");
        }
    }//GEN-LAST:event_bEstadoActionPerformed

    private void bFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFrequencyActionPerformed
        boolean estado = radio.getFrequency();
        if(estado == false){
            radio.setFrequency(true);
            lbFrequency.setText("FM");
        }
        else{
            radio.setFrequency(false);
            lbFrequency.setText("AM");
        }
    }//GEN-LAST:event_bFrequencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBackward;
    private javax.swing.JToggleButton bEstado;
    private javax.swing.JButton bForward;
    private javax.swing.JToggleButton bFrequency;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lbBoton;
    private javax.swing.JLabel lbEstacion;
    private javax.swing.JLabel lbFrequency;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pDisplay;
    // End of variables declaration//GEN-END:variables
}
